### ISSUE TITLE
Not able to set POST instead of GET for url service

### ISSUE THREAD

**Issue by plumblum** [jreese/znc-push#142]
So I'm using the python branch instead of the default one since that one won't build on my system, however it seems that the config is missing this option "message_uri_post" is this a known thing? or has something changed?

The option is not included in the description for the python branch but it's mentioned in the code for the actual service.

**Comment by jreese** [comment]
Not documented well, but the python branch uses the `target` option to select POST vs GET: https://github.com/jreese/znc-push/blob/python/push.py#L1402

Should be able to just do `/msg *push set target POST`.

**Comment by plumblum** [comment]
Nice thx!
