### ISSUE TITLE
1.6.0 support?

### ISSUE THREAD

**Issue by jacnoc** [jreese/znc-push#143]
Is znc 1.6.0 supported yet?
Worked fine in 1.4 but it doesn't appear to be working in 1.6.0 (I even used "send test" to test it and I'm not getting anything. (Sending a test message from the pushover website works fine). ).

**Comment by jacnoc** [comment]
Nevermind. Someone informed me that the python version (push.py) works with 1.6.0 (I can confirm that it does work).
(.so version does not)

**Comment by dgw** [comment]
I found that the .so version builds and works just fine with 1.6.0, but I installed all of ZNC 1.6.0's build dependencies and compiled from source; the module might not compile if you installed a prebuilt ZNC 1.6.0 package.

**Comment by Mikaela** [comment]
Also duplicate of https://github.com/jreese/znc-push/issues/141.
