### ISSUE TITLE
How to Compiling a module?

### ISSUE THREAD

**Issue by iruyanka** [jreese/znc-push#148]
http://wiki.znc.in/Compiling_modules

1. Save the module's source somewhere. Use <modulename>.cpp as the file name.
2. Run

NAS> znc-buildmod push.cpp
-ash: znc-buildmod: not found

I'm using ZNC on Synology. But this error.
How to Compiling a module?

**Comment by jreese** [comment]
You either need to build ZNC from source, or install a package that includes the ZNC headers and znc-buildmod command.  On Ubuntu, the package is named "znc-dev".  I have no idea what it would be for Synology, you will need to ask someone there.

**Comment by iruyanka** [comment]
Yes. I already installed ZNC on Synology.
I'm using Pushbullet of default Push module.

I can't install your Push module.

**Comment by jreese** [comment]
"znc-buildmod: not found" means the version of ZNC you installed is not able to compile third party modules.  You either need to find a ZNC package that includes znc-buildmod, or you need to build ZNC from source before you can build znc-push.

**Comment by Mikaela** [comment]
This would also be mentioned in ZNC's FAQ:

* http://wiki.znc.in/FAQ#I.27ve_installed_znc.2C_but_when_i_try_to_compile_modules_it_says_that_there_is_no_command_znc-buildmod
