### ISSUE TITLE
Private Massages / Public Massages

### ISSUE THREAD

**Issue by antonstarlid** [jreese/znc-push#151]
Thanks again for an awesome module, but something i miss is to see where the massage are come from.

I´m on like 15 networks, idle most of them and if someone send me a massage i can only see "#channel: [nick] massage" why not "network #channel: [nick] massage"

And same for private massages where i only can see "From nick: massage" why not "From network/nick massage"

I have look around a bit in the documentation but i have not found anyway to change this, and its really need to be done. I mean if you are like me, if you are in 5 networks whit your znc and not have them open in your irc. And the user is in all networks, you have to open every 5 networks to see where it where sanded.

\ Anton

**Comment by jreese** [comment]
This is configurable with the 'message_title` config option.  Eg, something like `/msg *push set message_title {network} {context}: {nick} {message}`.
