### ISSUE TITLE
Getting error when loading push module

### ISSUE THREAD

**Issue by Cydrobolt** [jreese/znc-push#166]
I'm getting the error

```
<cydrobolt> loadmod push
<*status> Unable to find modinfo [push] [Unable to open module [push] [/home/cydrobolt/.znc/modules/push.so: undefined symbol: _ZN7CModule17OnChanPermission2EPK5CNickRS1_R5CChanhbb]]
```
when trying to load the push module. I compiled everything according to the README. I am on Fedora 20

**Comment by jreese** [comment]
Sorry for the delay.  This is likely due to building a module against a different version of ZNC than what is running.  This can happen if you upgrade the ZNC package without restarting ZNC, or if your `znc-buildmod` binary came from a different source than your running ZNC instance.
