### ISSUE TITLE
Support a file path as load argument in OnLoad

### ISSUE THREAD

**Issue by btipling** [jreese/znc-push#169]
What I want is to have my push config loaded whenever znc restarts, and I'd like it to load that from what I gave to the save command.

Right now I have to update the push.cpp file and make every time I want to change options. It would be nice just to be able to /msg *push save ~/foo.txt and then put the path to ~/foo.txt as the argument in the znc.conf like so: `LoadModule = push ~/foo.txt` instead of having to rebuild and restart znc when I want to change highlights. Otherwise whenever my host reboots my server for maintenance I get no notifications anymore unless I remember to /msg *push load ~/foo.txt.

**Comment by btipling** [comment]
Seems like it would be doable by taking the load command pieces, putting that in a function and calling on a 'load' and calling it in the OnLoad znc hook if an arg is provided.

**Comment by jreese** [comment]
You shouldn't need to rebuild znc-push just to make changes to your preferences.  You can just do something like `/msg *push set highlight foo`, and it will automatically persist those preferences across restarts of ZNC.  The `save` and `load` commands should only be needed for exporting and importing options between multiple instances or users of ZNC.

**Comment by btipling** [comment]
It doesn't automatically persist those things. Does it for you? Where in the code do you see it populate the protected property `defaults` from anywhere as that's how it sets options in OnLoad. By iterating over defaults.

**Comment by jreese** [comment]
`defaults` should always reflect what the module is compiled with, but nothing directly references what's in the `defaults` dictionary.  Everything reads from the `options` dictionary, which is pre-populated from `defaults`, and then immediately loads values from the user's ZNC configuration, eg `~/.znc/users/<user>/moddata/push/.registry`.

**Comment by btipling** [comment]
Ok I just tried it and you're right that works. I don't know why I thought it didn't. Thank you, and thank you for making this plugin. It works great with my pebble time. :)
