### ISSUE TITLE
"Inverted" replied yes [Feature Request] 

### ISSUE THREAD

**Issue by DangerDane** [jreese/znc-push#177]
Someone using my ZNC today actually asked me the following in regards to using the push module. And just wondering if something like this is posible with the present settings, which I think it isn't and thus why I am submitting this feature request...

He wants it so that it keeps sending push message to him from PM or channel UNTIL he responds, at which point it shouldn't push anymore. Then after x amount of time of inactivity has passed it should start pushing again if PM's or highlights gets triggered.

But not even sure if it is possible.

**Comment by jreese** [comment]
This should be possible by setting something like `replied: no, last_notification: 0, last_active: 60`.

**Comment by DangerDane** [comment]
so like set channel_conditions: highlight replied: no last_notification: 0 last_active: 3600 or does each "option" need a , between it?

**Comment by jreese** [comment]
well, each one needs to be set separately, but also, you should be able to leave `channel_conditions` alone.  `set channel_conditions highlight` would ignore all other values altogether, and just spam notifications for every PM or channel mention.  See the example configs for some better explanation on some of these options:  https://github.com/jreese/znc-push/blob/master/doc/examples.md

**Comment by DangerDane** [comment]
Thanks a lot
