### ISSUE TITLE
[python] make install fails with sed: can't read : No such file or directory

### ISSUE THREAD

**Issue by mgedmin** [jreese/znc-push#180]
Steps to reproduce:

1. git clone -b python https://github.com/jreese/znc-push
2. cd znc-push
3. make install

What happens:

```
$ make install
cp push.py push.copy.py
sed -i "" -e "s|VERSION = '.*'|VERSION = 'v2.0.0-rc-53-gb7a4a77'|" push.copy.py
sed: can't read : No such file or directory
make: *** [push.pyc] Error 2
```

OS: Ubuntu 14.04.2 LTS

**Comment by mgedmin** [comment]
Changing the Makefile to run `sed -i -e "..." push.copy.py"` fixes this.

**Comment by mgedmin** [comment]
I was about to submit a pull request, but then I noticed 66d91f251b749e6ca280b24c84e31a1bcdc9fad3, so you must've added that `""` for a reason.  What was it?

Perhaps you can use
```
sed -e "..." < push.py > push.copy.py.tmp && mv push.copy.py.tmp push.copy.py
```
and avoid inplace modification altogether?

**Comment by jreese** [comment]
Hmm, this seems to be an incompatibility between BSD sed and GNU sed.  I recently switched to using a Mac for my dev work.  I'll find a way that works with both platforms.
