### ISSUE TITLE
[feature-req] Can you support Telegram Bot?

### ISSUE THREAD

**Issue by iruyanka** [jreese/znc-push#187]
https://core.telegram.org/bots/api
http://domoticz.com/wiki/Telegram_Bot#Using_Telegram_Bot_to_Send_Messages_with_Curl

I guess Telegram Bot is very good. I want it. Thanks.

**Comment by florian-184-de** [comment]
+1

**Comment by mrrcollins** [comment]
I just added this to my personal copy, I didn't think there would be any demand for it to be added!

Let me clean up my code and test it, and then I'll submit a pull request.

**Comment by rctgamer3** [comment]
@mrrcollins any progress yet?

**Comment by urbels** [comment]
+ for telegram bot

**Comment by jessesung** [comment]
Sent a PR for supporting telegram: https://github.com/jreese/znc-push/pull/202

**Comment by mapreri** [comment]
Telegram support has been merged, so IMHO this can be closed now.
