### ISSUE TITLE
[Python] Per-channel highlight

### ISSUE THREAD

**Issue by Mikaela** [jreese/znc-push#188]
I am op on some channels, but I am also on channels where I am not op.

On the channels where I am op, I would like to highlight on `*!ops*` so I know if op attention is wanted somewhere.

Currently it seems that I must either `/msg *push append highlight *!ops*` and get op-summons on all channels or not highlight at it at all.

**Comment by jreese** [comment]
This is supported in the python version.  `/msg *push set|append network|#channel <key> <value>` should do the trick.  For various reasons, this is likely to be unsupported on the C++ side.

**Comment by Mikaela** [comment]
Nice, that should probably be documented clearly somewhere.
