### ISSUE TITLE
README - custom URL - confused how to use it

### ISSUE THREAD

**Issue by dreamcat4** [jreese/znc-push#194]
Hi,
In your README.md file, there is this line:

> When using the custom URL service, this options allows you to specify the URL to send a GET request to, and has keyword expansion performed on portions of it, including the path and any query parameter values.

However it is written below an option which does not seem to match it (as is an integer number for max message length).

What is not clear is to which other option this text is meant to refer to, because there is both 'message' and 'uri to send with the message'. It could be for either variable.

Perhaps some real-life example would be helpful to demonstrate correct usage. And which of those fields (message or URI) are not-used / can be left blank.

**Comment by dreamcat4** [comment]
Ah,
It is `message_uri`

```
17:40:58 <znc_user> set service url
17:40:58 <...*push> Note: URL requires setting the 'message_uri' option with the full URL
```

**Comment by jreese** [comment]
Looks like this was a victim of various reorganization and/or merge conflicts.  Thanks for pointing it out!
