### ISSUE TITLE
How to properly set context for highlights from specific channel?

### ISSUE THREAD

**Issue by piejanssens** [jreese/znc-push#209]
I want to match messages containing both the words foo and bar in a specific #channel.
I was thinking of doing this: `/msg *push set context #channel foo bar`

*push returns "Error: invalid option name "

And I read in the readme that " Strings will be compared in order they appear in the configuration value, and the first string to match will end the search, meaning that earlier strings take priority over later values.". So I don't understand how to match both foo and bar in one message.

**Comment by jreese** [comment]
a) you're trying to set an incorrect config name.  I suspect you're wanting the `highlight` option.
b) you should be able to accomplish this with wildcards.  The asterisk matches anything, but you'd need to list all possible arrangements.  eg, `/msg *push set highlight foo*bar bar*foo`.

**Comment by piejanssens** [comment]
But what if I only want highlights from a particular channel?

**Comment by jreese** [comment]
That feature is available in the python branch, using something like `/msg *push set highlight #channel foo bar`, though that branch doesn't have the support for wildcards, and has known bugs when dealing with multiple networks or users.
