### ISSUE TITLE
Build Issue with PUSHVERSION

### ISSUE THREAD

**Issue by clem16** [jreese/znc-push#212]
I might be doing something wrong, but I have been getting an issue with my build.
From what I can deduce the build is choking on multiple decimal points in the PUSHVERSION variable set by the Makefile.
If I go into the makefile and I set the PUSHVERSION to something like 1 it all works fine. But then the module is not reporting the correct version and I find this annoying...

Any suggestions?

Here's a link to what I get in terminal - same as what's quoted below.
http://pastebin.com/h9rqj9i0

>  make
CXXFLAGS=" -DPUSHVERSION=\"v1.0.0-143-gcf08b9e\" " LIBS=" " \
	 znc-buildmod push.cpp
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZNC 1.7.x
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmprwky999l
make[1]: Entering directory '/tmp/tmprwky999l'
make[2]: Entering directory '/tmp/tmprwky999l'
make[3]: Entering directory '/tmp/tmprwky999l'
Scanning dependencies of target module_push
make[3]: Leaving directory '/tmp/tmprwky999l'
make[3]: Entering directory '/tmp/tmprwky999l'
[ 50%] Building CXX object CMakeFiles/module_push.dir/home/clem/znc-push/push.cpp.o
<command-line>:0:15: error: too many decimal points in number
/home/clem/znc-push/push.cpp:57:39: note: in expansion of macro ‘PUSHVERSION’
    user_agent = "ZNC Push/" + CString(PUSHVERSION);
                                       ^
<command-line>:0:15: error: too many decimal points in number
/home/clem/znc-push/push.cpp:1772:37: note: in expansion of macro ‘PUSHVERSION’
     PutModule("znc-push " + CString(PUSHVERSION));
                                     ^
/home/clem/znc-push/push.cpp: In constructor ‘CPushSocket::CPushSocket(CModule*)’:
<command-line>:0:13: error: ‘v1’ was not declared in this scope
/home/clem/znc-push/push.cpp:57:39: note: in expansion of macro ‘PUSHVERSION’
    user_agent = "ZNC Push/" + CString(PUSHVERSION);
                                       ^
/home/clem/znc-push/push.cpp: In member function ‘virtual void CPushMod::OnModCommand(const CString&)’:
<command-line>:0:13: error: ‘v1’ was not declared in this scope
/home/clem/znc-push/push.cpp:1772:37: note: in expansion of macro ‘PUSHVERSION’
     PutModule("znc-push " + CString(PUSHVERSION));
                                     ^
CMakeFiles/module_push.dir/build.make:62: recipe for target 'CMakeFiles/module_push.dir/home/clem/znc-push/push.cpp.o' failed
make[3]: *** [CMakeFiles/module_push.dir/home/clem/znc-push/push.cpp.o] Error 1
make[3]: Leaving directory '/tmp/tmprwky999l'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/module_push.dir/all' failed
make[2]: *** [CMakeFiles/module_push.dir/all] Error 2
make[2]: Leaving directory '/tmp/tmprwky999l'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/tmprwky999l'
Traceback (most recent call last):
  File "/usr/local/bin/znc-buildmod", line 96, in <module>
    subprocess.check_call(['cmake', '--build', '.'], cwd=build)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2
Makefile:13: recipe for target 'push.so' failed
make: *** [push.so] Error 1

**Comment by jreese** [comment]
What OS are you building this on?

**Comment by clem16** [comment]
Oh! Sorry! I should have included that. In all honesty, it's a bit of an odd setup. It's running on a Raspberry Pi. Running Raspbian. Simple, small, low power, no annoying fan noise. That's the whole idea anyways.
here's the uname -a
Linux atom 4.4.26+ #915 Thu Oct 20 17:02:14 BST 2016 armv6l GNU/Linux

**Comment by jreese** [comment]
Try a clean checkout, and building manually with `znc-buildmod push.cpp`.

**Comment by Shaxine** [comment]
@jreese I had the same problem and:`znc-buildmod push.cpp` did the trick.

Just for the record `make curl=yes` and `make` worked just fine when `znc` and `znc-dev` were installed from repository (znc 1.4).

This error only occurred after compiling and installing znc 1.7.x from source.

**Comment by jreese** [comment]
Afaik, you won't be able to use curl with `znc-buildmod` because it doesn't provide a mechanism for passing the appropriate values to the compiler.

**Comment by GRMrGecko** [comment]
My solution is to replace `-DPUSHVERSION=\"$(version)\"` with `-DPUSHVERSION=\"\\\"$(version)\\\"\"` in the Makefile. New znc-buildmod seems to treating strings differently.
