### ISSUE TITLE
Compatibility to ZNC 1.6.4

### ISSUE THREAD

**Issue by keigel2001** [jreese/znc-push#214]
ZNC 1.6.4 changed to OpenSSL 1.1, which has a new API, that isn't fully compatible to previous versions.
In consultation with jreese I created this issue to track if znc-push is affected by these changes.

**Comment by Mikaela** [comment]
I haven't noticed any issues with git, so I don't think *push should have any issue with 1.6.4.

I have used the Python version since ages ago as it was going to replace the c++ version which I hope is still the case though.

**Comment by keigel2001** [comment]
I've now also updated and URL service with CSocket is working like expected.
