### ISSUE TITLE
ZNC Bouncer - unRAID

### ISSUE THREAD

**Issue by jrdnlc** [jreese/znc-push#220]
Anyone have running the ZNC bouncer on a docker and able to setup ZNC?  I'm having trouble on what's the procedure on how it's done properly.

Any help will be greatly appreciated. Thanks!

**Comment by stevesbrain** [comment]
@jrdnlc Not really a znc-push issue from what I can tell? However, for a Docker container that runs ZNC *with* push module built as part of the image, please see:

https://hub.docker.com/r/vanityshed/znc-alpine-push/
