### ISSUE TITLE
Channel highlight push notifications not working

### ISSUE THREAD

**Issue by kobuki** [jreese/znc-push#221]
I'm new to znc-push so it's possible I made a mistake somewhere. I can't seem to receive highlights of my nick when said on channels. I do get notifications of private messages on the same network. I'm using Pushover. All settings are on default, but the higlight and Pushover credentials.

Higlight settings: set highlight mynick mynick* *mynick \*mynick\*

Do I need something else? Can I debug higlight matches somehow?

**Comment by jreese** [comment]
I think this is covered by the FAQ: https://github.com/jreese/znc-push/blob/master/doc/faq.md#why-dont-i-get-notifications

You can `set debug on` if you would like extra information on what's going on.

**Comment by kobuki** [comment]
OK, it worked on a channel. Not on another one on another network. Will need to investigate more.
