### ISSUE TITLE
Which branch moving forward?

### ISSUE THREAD

**Issue by stevesbrain** [jreese/znc-push#224]
Hey @jreese - I know previously it's been mentioned that the python branch was going to be the future moving forward, but I've noticed that's had no commits for ~6 months, whilst master/C branch has had a few commits this year. 

Has the plan changed, or will python still be "the future"? Just want to make sure I'm using the right stuff, and building my docker images with the right stuff for others as well :)

**Comment by jreese** [comment]
There are still some blocking issues with the Python branch, like failing on multi-user instances, but I haven't had much time to work on the branch.  For the time being, the master branch should still be considered the "official" version of znc-push.

**Comment by stevesbrain** [comment]
No worries - appreciate the response @jreese :)
