### ISSUE TITLE
User loaded module, context setting question

### ISSUE THREAD

**Issue by stevesbrain** [jreese/znc-push#234]
I notice that setting context for a channel negation would be in the format of: -#channelname

However, I load my module as a user module. Is there any way to negate one network's #channelname but not another? For example, to block Freenode's #vim but allow OFTC's #vim I would expect to be:
```
/msg *push set context -freenode.#vim *
```

But it appears to ignore the network name. Am I doing this wrong, or is this simply not supported yet? Thanks!

**Comment by jreese** [comment]
Not currently supported on master.  The experimental python version would support this via network-specific config values, but there are KP's with multi-user setups.

**Comment by dgw** [comment]
Python can cause kernel panics? 😆

**Comment by jreese** [comment]
LOL, Known Problems 😉

**Comment by stevesbrain** [comment]
Great, thanks for confirming @jreese !
