### ISSUE TITLE
trouble shooting

### ISSUE THREAD

**Issue by CGCode1000** [jreese/znc-push#263]
Apologies if I should not be posting this issue here but I have no where else to go :(

Push has been working with Prowl service for many years and suddenly stopped working around 5 days ago (10/16/21). 

Sending a message with Push in debug mode shows notification build info as expected and ends with "Request sending" however no message is received. It appears to be an issue with ZNC server as I have tried multiple alert services. I am intimately familiar with the various settings and parameters that the Push module takes and I am certain they are correct. I have also compiled and installed every version of Push I could find and none seem to send a message. 

My question is how can I further troubleshoot? What logs would I need to look at on the server?

**Comment by dgw** [comment]
More should happen after that. See if you can get output from ZNC's debug option (based on [the default implementation of `CSocket::SockError()`](https://github.com/znc/znc/blob/ac57c0e524fcc0879871c3e535df660fead4118e/src/Socket.cpp#L519-L526)), or you could recompile your copy of znc-push with its own `virtual void SockError(int iErrno, const CString& sDescription)` implementation that sends debug output to `*push` over IRC with everything else if you really want. (Handling errors with znc-push's own debug option could be a useful patch, actually.)

**Comment by CGCode1000** [comment]
understood-  I will focus on ZNC's built in debug option. Thanks so much for your help, quick responses and time spent.
