### ISSUE TITLE
Doesn't push to Boxcar

### ISSUE THREAD

**Issue by Bensge** [jreese/znc-push#27]
I compiled and installed the module on my vps (centos 5) and configured it.
I got a notification in boxcar once that znc was added to my services.
However mentions / private messages don't get pushed to boxcar.
I didn't set "secret" because i couldn't find it on the boxcar website and the readme shows to use subscribe instead. Do i have to set this too?

**Comment by jruels** [comment]
Hello,
I am trying to get this working with boxcar and I'm running into an issue.  The steps I used were: 
/msg *push set debug on
/msg *push set service boxcar
/msg *push set username myemail@domain.tld
/msg *push subscribe

When I try to subscribe I get a 403 Forbidden error.  
I have tried both the email I signed up for boxcar with, as well as the notification email from boxcar settings and neither worked. 

What am I missing? 

Thanks!

**Comment by jreese** [comment]
It's possible that Boxcar has changed their API.  I don't have a good way to test this service though, so I can't really help track down the solution.  Sorry.

**Comment by DataRepository** [comment]
I left the 'username' and 'secret' field blank for BoxCar. But when I try to issue /msg *push subscribe it tells me "Error: username not set". What username am I supposed to put in? In BoxCar's app there is no username for me to fill in.

**Comment by bhaap** [comment]
http://help.boxcar.io/support/solutions/articles/6000004813-how-to-send-a-notification-to-boxcar-for-ios-users

jreese that is their API guide. I guess that you have to use the API key from the app to auth now. Should not be so hard to implement this change?
