### ISSUE TITLE
Boxcar push don't work.

### ISSUE THREAD

**Issue by dcmwai** [jreese/znc-push#63]
It seem that something was wrong boxcar don't work.

It show a 404 Not found after Query

_push> Building notification to boxcar.io/devices/providers/pxxxxxxxxxxxxxxxxxxb9/notifications...
<_push> Query string: email=%3D+%22asdasd%40gmail.com%22&notification%5Bfrom_screen_name%5D=%2Apush&notification%5Bmessage%5D=%3Ctest+message%3E&notification%5Bsource_url%5D=
<_push> Request sending
<_push> Ok
<_push> 404
<_push> Not Found
<_push> Content-Type: text/html; charset=utf-8
<_push> Content-Length: 1
<_push> Connection: close
<_push> Status: 404 Not Found
<_push> Cache-Control: no-cache
<_push> X-Runtime: 5
<_push> Set-Cookie: _boxcar-api_session=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc; path=/; HttpOnly
<_push> X-Powered-By: Phusion Passenger 4.0.23
<_push> Date: Mon, 13 Jan 2014 00:56:23 GMT
<_push> Server: nginx/1.4.3 + Phusion Passenger 4.0.23
<*push>

**Comment by DataRepository** [comment]
jreese, are you still aware of any issues with Boxcar?

**Comment by jreese** [comment]
I'm not aware of any issues, but I don't use Boxcar or have an iPhone to confirm one way or the other.
