### ISSUE TITLE
PushBullet notifications do not work

### ISSUE THREAD

**Issue by mgedmin** [jreese/znc-push#80]
Ubuntu 12.04, znc 0.206, znc-push built without curl support (because of #78).

```
/msg *status load push
/msg *push set service pushbullet
/msg *push set secret ...
/msg *push set target ...
/msg *push set debug on
/msg *push send waah
```

I see

```
<*push> service: pushbullet
 service_host: api.pushbullet.com
 service_url: /api/pushes
 service_auth: ...
 use_port: 443
 use_ssl: 1
 use_post: 1
 NOT using libcurl
 Building notification to api.pushbullet.com/api/pushes...
 Query string: body=waaah&device_iden=...&title=New+Message&type=note
 Request sending
 Ok
```

and yet the message doesn't reach my phone.

Testing with curl on the command line shows that all the arguments and secret keys are correct:

```
curl https://api.pushbullet.com/api/pushes -u $SECRET: -d body=ohffs -d title=zomg -d device_iden=$ID -d type=note -X POST
```

**Comment by duck57** [comment]
It seems that there may have been a PushBullet update sometime in the past few months that broke my PushBullet integration.  I just generated a new PushBullet API key and set it as my secret, then used `send` to give myself a test message.  `*push` said `Ok`, but then I did not receive the notification on my phone or when I signed into the PushBullet website.

**Comment by mgedmin** [comment]
(For the record, PushBullet notifications also have stopped working for me a few months ago.  Before that I was using the Python version of this plugin with great success.)

**Comment by Cabji** [comment]
Unsure if i have it set up correctly, but i am not seeing any push messages from znc push using pushbullet either. I get the ok from *push and a log like the one here in the original post.

**Comment by mgedmin** [comment]
> (For the record, PushBullet notifications also have stopped working for me since a few months ago. Before that I was using the Python version of this plugin with great success.)

That was a total PEBKAC.  I'd configured push.py to specify a device ID and then forgot to update it when I upgraded to a new phone.

**Comment by Merlincool** [comment]
> My problem is solved -- with the patches in https://github.com/mgedmin/znc-push master and one hacky fix in /usr/bin/znc-buildmod I now have a libcurl-enabled fully-functional znc-push.so that works with the ancient ZNC in Ubuntu 12.04 LTS. (14.04 LTS will be out in three days and maybe I'll finally be able to upgrade!)
> 
> I was trying to provide information to help you debug/fix the problems that may still exist in master, for people who build with libcurl disabled.

I am sorry to dig you after long time, what exactly did you do for fix?

**Comment by mgedmin** [comment]
> I am sorry to dig you after long time, what exactly did you do for fix?

I myself don't remember, but you can see the commits at https://github.com/mgedmin/znc-push/commits/master.

I switched to the Python branch later, which has been and is still working faithfully.
